package main

//-----------
const Act_Add_Sick string = "add-sick---"
const Act_Add_Risk string = "add-risk---"
const Act_Add_Nurse string = "add-nurse--"
const Act_Add_Follow string = "add-follow-"
const Act_User_Login string = "user-login-"
const Act_Search_Sisk string = "search-sisk"
const Act_Search_detail_Sick string = "-ser-det-s-"
const Act_Serch_Cycle string = "-ser-cycle-"
const Act_Req_Risk string = "-req-risk--"
const Act_Search_Nurse_Table string = "-sea-nurs-t"
const Act_Req_Nurese string = "-req-nurse-"
const Act_Req_Follow string = "-req-follow"
const Act_Seach_Out_Hospital string = "-sea-out---"
const Act_Search_Wait string = "-sea-wait--"
const Act_Search_Follow_Table string = "-sea-foll-t"
const Act_Search_Height_Risk string = "-seq-h-risk"
const Act_Req_Cylce_Last string = "req-cycle-l"
const Act_Search_Today_Nurse string = "sea-to-nurs"
const Act_Req_Last_Not_Medication string = "sea-lnot-me"
